### PR TITLE
Add tracing flags to CLI.

### PR DESCRIPTION
**Pull request by cpuguy83**
Adds support for using ocagent to export tracing data.

### CODE REVIEW

**Comment by cpuguy83** [comment]
Tests are getting 409 service unavailable in westus.

**Comment by ibabou** [comment]
> Tests are getting 409 service unavailable in westus.

@cpuguy83  Can you try re-running the tests ?

**Comment by cpuguy83** [comment]
Failed again with 409 in westus.

**Comment by cpuguy83** [comment]
Is there a better region to run tests against?

**Comment by ibabou** [comment]
> Is there a better region to run tests against?

you can try eastus. more capacity there

**Comment by cpuguy83** [comment]
Sadly this seems to be hardcoded into the tests.

**Comment by cpuguy83** [comment]
Woohoo, all green now.

**Pull request merged**
